ITEM_DICT = {
    "Cabbage": {
        "gatherable_type": "Growing",
        "quality": {
            "season": "Autumn w2",
            "poo": "Sheep",
            "weather": "Windy",
            "tool": "Adept+",
        },
        "location": ["Garden"],
        "price": [1, 2, 3, 3, 4],
    },
    "Iris": {
        "gatherable_type": "Growing",
        "quality": {
            "season": "Spring",
            "time": {"Morning", "Turnsday (4)"},
            "weather": "Hot",
        },
        "location": [
            "Wisptrail",
            "Copperpot",
            "Frogmarsh",
            "Greymarket",
            "Dreadwaters",
        ],
        "price": [2, 3, 4, 4, 6],
    },
    "PinkRose": {
        "gatherable_type": "Growing",
        "quality": {
            "season": "Spring",
            "time": {"Even days", "Evening"},
            "weather": "Rain",
        },
        "location": ["Mellowbrook", "The Twanging Gardens"],
        "price": [1, 2, 3, 3, 4],
    },
    "SongstrellFlower": {
        "gatherable_type": "Growing",
        "quality": {
            "season": "Spring",
            "time": {"Morning", "Dawn"},
            "has": "Partner",
        },
        "location": ["Simplewood", "Tir Na Nog"],
        "price": [2, 4, 5, 6, 7],
    },
    "Lettuce": {
        "gatherable_type": "Growing",
        "quality": {
            "season": "Spring w1",
            "poo": "Pig",
            "tool": "Artisan+",
            "location": "Home",
        },
        "location": ["Garden"],
        "price": [1, 2, 3, 3, 4],
    },
    "Radish": {
        "gatherable_type": "Growing",
        "quality": {
            "season": "Spring w2",
            "poo": "Sheep",
            "tool": "Journeyman+",
            "follower": "Pig",
        },
        "location": ["Garden"],
        "price": [1, 2, 3, 3, 4],
    },
    "Cavewort": {
        "gatherable_type": "Growing",
        "quality": {
            "season": "Summer",
            "time": {"Dawn/Dusk"},
            "ride": "Pig",
            "weather": "Rain",
        },
        "location": ["Lair", "Deep Mine"],
        "price": [1, 2, 3, 3, 4],
    },
    "Sunflower": {
        "gatherable_type": "Growing",
        "quality": {
            "season": "Summer",
            "poo": "Pig",
            "time": {"Morning"},
            "weather": "Sunny",
        },
        "location": ["Cunning Plots", "The Twanging Gardens"],
        "price": [1, 1, 1, 1, 1],
    },
    "Barley": {
        "gatherable_type": "Growing",
        "quality": {
            "season": "Summer w2",
            "poo": "Sheep",
            "time": {"Dawn"},
            "tool": "Apprentice+",
        },
        "location": ["Mellowbrook"],
        "price": [1, 1, 2, 2, 3],
    },
    "Leek": {
        "gatherable_type": "Growing",
        "quality": {
            "season": "Summer w2",
            "poo": "Sheep",
            "time": {"Morning"},
            "follower": "Fillifryth",
        },
        "location": ["Woemarsh"],
        "price": [1, 2, 3, 3, 4],
    },
    "Drumstick": {
        "gatherable_type": "Growing",
        "quality": {
            "time": {"Morning"},
            "season": "Summer w2",
            "weather": "Hot",
            "follower": "Cat",
        },
        "location": ["Garden"],
        "price": [2, 4, 5, 6, 7],
    },
    "Carrot": {
        "gatherable_type": "Growing",
        "quality": {
            "season": "Winter w1",
            "poo": "Pig",
            "follower": "Pig",
            "tool": "Craftsman+",
        },
        "location": ["Candlewych West", "Cowpat Farm", "Testy Acres"],
        "price": [1, 1, 2, 2, 3],
    },
    "Turnip": {
        "gatherable_type": "Growing",
        "quality": {
            "season": "Winter w1",
            "poo": "Sheep",
            "has": "Partner",
            "tool": "Craftsman+",
        },
        "location": ["Willowdown Farm"],
        "price": [1, 1, 2, 2, 3],
    },
    "Pumpkin": {
        "gatherable_type": "Growing",
        "quality": {
            "season": "Winter w2",
            "poo": "Sheep",
            "trait": "Strength",
            "tool": "Adept+",
        },
        "location": ["Garden"],
        "price": [2, 3, 4, 4, 6],
    },
    "Funflower": {
        "gatherable_type": "Growing",
        "quality": {
            "time": {"Dusk", "Afternoon"},
            "weather": "Foggy",
            "trait": "Scent",
        },
        "location": ["The Twanging Gardens", "Tir Na Nog"],
        "price": [4, 4, 4, 4, 4],
    },
    "Heartroot": {
        "spawn": {"time": {"Odd days"},},
        "gatherable_type": "Growing",
        "quality": {
            "weather": "Pollen",
            "has": "Partner",
            "poo": "Sheep",
            "tool": "Master+",
        },
        "location": ["E'ergreen", "Simplewood"],
        "price": [8, 13, 17, 20, 25],
    },
    "Pork": {
        "gatherable_type": "Growing",
        "quality": {
            "weather": "Blizzard",
            "follower": "Dog",
            "poo": "Sheep",
            "tool": "Adept+",
        },
        "location": ["Garden"],
        "price": [2, 4, 5, 6, 7],
    },
    "Barbel": {
        "spawn": {"time": {"Evening"},},
        "gatherable_type": "Fishing",
        "quality": {
            "time": {"Dusk"},
            "weather": "Mild",
            "trait": "Strength",
            "tool": "Journeyman+",
        },
        "location": [
            "Freyl's Fields",
            "Mellowbrook",
            "Outlane",
            "The Twanging Gardens",
        ],
        "price": [3, 5, 7, 8, 10],
    },
    "Bluefish": {
        "spawn": {"time": {"Night"}, "season": {"Summer", "Winter", "Autumn"},},
        "gatherable_type": "Fishing",
        "quality": {
            "season": "Winter",
            "tool": "Adept+",
            "weather": "Blizzard",
            "has": "Hater",
        },
        "location": ["Mellowfield ponds"],
        "price": [3, 4, 6, 7, 9],
    },
    "CheckeredChub": {
        "spawn": {"season": {"Spring", "Winter", "Autumn"},},
        "gatherable_type": "Fishing",
        "quality": {
            "season": "Winter",
            "weather": "Snowing",
            "tool": "Journeyman+",
            "trait": "Toughness",
        },
        "location": [
            "Burial Grounds",
            "Cuckoo Wood",
            "Festival Green",
            "Candlewych West",
        ],
        "price": [2, 3, 4, 4, 6],
    },
    "Cointail": {
        "spawn": {"area": "Waterfall",},
        "gatherable_type": "Fishing",
        "quality": {
            "season": "Spring",
            "weather": "Sunny",
            "tool": "Master+",
            "time": {"Even days"},
        },
        "location": ["Cowpat Farm", "Cuckoo Wood", "Testy Acres"],
        "price": [2, 4, 5, 6, 7],
    },
    "Cursefish": {
        "spawn": {"weather": "Storm",},
        "gatherable_type": "Fishing",
        "quality": {
            "season": "Autumn",
            "tool": "Expert+",
            "trait": {"Clumsy", "Flatulent"},
        },
        "location": ["Dreamer's Nook", "Cowpat Farm", "Tir Na Nog", "Willowdown Farm"],
        "price": [3, 5, 7, 8, 10],
    },
    "Eel": {
        "spawn": {"time": {"Night"}, "area": "River"},
        "gatherable_type": "Fishing",
        "quality": {"weather": "Rain", 
        "tool": "Craftsman+", 
        "trait": "Intelligence",
        
        },
        "location": [
            "FineFayre",
            "Mellowbrook",
            "Outlane",
            "Poppyhill",
            "Willowdown Farm",
        ],
        "price": [1, 2, 3, 3, 4],
    },
    "Firefish": {
        "spawn": {
            "season": {"Summer", "Winter", "Spring"},
            "weather": "Sunny",
            "area": "Pools",
        },
        "gatherable_type": "Fishing",
        "quality": {
            "season": {"Summer", "Summer w1"},
            "weather": "Not Rain",
            "tool": "Master+",
        },
        "location": ["Cowpat", "Cuckoo Wood", "Rivermoor", "Tir Na Nog"],
        "price": [10, 16, 20, 24, 30],
    },
    "FishOfManyFingers": {
        "spawn": {"time": {"Afternoon"}},
        "gatherable_type": "Fishing",
        "quality": {
            "season": {"Winter"},
            "weather": "Under Moonbeams",
            "tool": "Legendary+",
            "follower": "Fillifryth",
        },
        "location": ["E'ergreen"],
        "price": [4, 6, 8, 9, 12],
    },
    "FishieWishie": {
        "spawn": {"time": {"Night"}},
        "gatherable_type": "Fishing",
        "quality": {
            "weather": "Bubbles",
            "tool": "Legendary+",
            "time": {"Even days"},
            "trait": "Intelligence",
        },
        "location": ["Tir Na Nog"],
        "price": [5, 8, 10, 12, 15],
    },
    "Flagfish": {
        "spawn": {"season": {"Summer", "Autumn", "Spring"},},
        "gatherable_type": "Fishing",
        "quality": {
            "season": "Spring w1",
            "weather": "Windy",
            "time": {"Dawn"},
            "tool": "Craftsman+",
        },
        "location": [
            "Rivermoor",
            "Homesteads",
            "Poppyhill",
            "FestField",
            "Naida's Glory",
            "Loverwood",
            "Drownhill",
            "The Shoe",
        ],
        "price": [5, 8, 10, 12, 15],
    },
    "Flickerfin": {
        "spawn": {"time": {"Dusk", "Evening"},},
        "gatherable_type": "Fishing",
        "quality": {
            "tool": "Adept+",
            "weather": "Bubbles",
            "time": {"Dusk"},
            "trait": "Constitution",
        },
        "location": ["Tir Na Nog"],
        "price": [5, 8, 10, 12, 15],
    },
    "Gasbelly": {
        "spawn": {"time": {"Morning", "Dawn"},},
        "gatherable_type": "Fishing",
        "quality": {
            "tool": "Expert+",
            "weather": {"Windy", "Eclipse"},
            "time": {"Dawn"},
        },
        "location": ["Wisptrail", "Copperpot", "Frogmarsh", "Greymarket"],
        "price": [2, 4, 5, 6, 7],
    },
    "Lorianthe": {
        "spawn": {"time": {"Morning", "Dawn"},},
        "gatherable_type": "Fishing",
        "quality": {
            "tool": "Master+",
            "time": "Dawn",
            "season": {"Summer", "Autumn", "Winter"},
            "trait": "Intelligence",
        },
        "location": ["E'ergreen"],
        "price": [3, 4, 6, 7, 9],
    },
    "Minnow": {
        "spawn": {"time": {"Morning", "Dawn"},},
        "gatherable_type": "Fishing",
        "quality": {
            "tool": "Apprentice+",
            "time": "Dawn",
            "season": {"Autumn"},
            "trait": "Speed",
        },
        "location": ["Summerdown"],
        "price": [2, 3, 4, 4, 6],
    },
    "Moonfish": {
        "spawn": {"time": {"Night", "Even days"}, "area": "Ponds"},
        "gatherable_type": "Fishing",
        "quality": {
            "misc": "Lantern Off",
            "weather": {"Eclipse"},
            "season": "Spring",
            "tool": "Master+",
        },
        "location": ["Everywhere"],
        "price": [10, 16, 20, 24, 30],
    },
    "Mudkipper": {
        "spawn": {"season": {"Spring", "Winter", "Autumn"}},
        "gatherable_type": "Fishing",
        "quality": {
            "time": "Afternoon",
            "weather": {"Rain"},
            "season": "Autumn",
            "tool": "Journeyman+",
        },
        "location": ["Everywhere"],
        "price": [2, 3, 4, 4, 6],
    },
    "Needlenip": {
        "spawn": {"time": {"Evening"},},
        "gatherable_type": "Fishing",
        "quality": {
            "follower": "Bumbabloopfnoop",
            "tool": "Master+",
            "misc": "Lantern Off",
            "trait": "Illusion",
        },
        "location": ["E'ergreen"],
        "price": [3, 4, 6, 7, 9],
    },
    "OffalTench": {
        "spawn": {"time": {"Morning", "Dawn"},},
        "gatherable_type": "Fishing",
        "quality": {
            "time": {"Dawn"},
            "follower": "Has Greens",
            "trait": "Scent",
            "tool": "Artisan+",
        },
        "location": [
            "Candlewych Cottage/Village",
            "Cowpat Farm",
            "Cuckoo Wood",
            "Mosswhisper Ruin",
        ],
        "price": [3, 4, 6, 7, 9],
    },
    "Pike": {
        "spawn": {"time": {"Dusk", "Dawn"}, "area": "River",},
        "gatherable_type": "Fishing",
        "quality": {
            "time": {"Dawn", "Even days"},
            "trait": "Intelligence",
            "tool": "Craftsman+",
        },
        "location": [
            "Candlewych Cottage/Village",
            "Cowpat Farm",
            "Cuckoo Wood",
            "Mosswhisper Ruin",
        ],
        "price": [3, 4, 6, 7, 9],
    },
    "Pondlurker": {
        "spawn": {"time": {"Morning", "Dawn", "Afternoon"},},
        "gatherable_type": "Fishing",
        "quality": {
            "weather": "Sunny",
            "season": "Spring",
            "tool": "Journeyman+",
            "time": "Freylsday (5)",
        },
        "location": ["Vale"],
        "price": [1, 1, 1, 1, 1],
    },
    "Rainfish": {
        "spawn": {"weather": {"Rain"},},
        "gatherable_type": "Fishing",
        "quality": {
            "tool": "Adept+",
            "time": "Dusk",
            "weather": "Storm",
            "misc": "Rainstick",
        },
        "location": ["Everywhere"],
        "price": [1, 2, 3, 3, 4],
    },
    "RiverTrout": {
        "spawn": {"time": {"Evening", "Dusk"}, "area": "River",},
        "gatherable_type": "Fishing",
        "quality": {
            "tool": "Apprentice+",
            "time": "Dusk",
            "season": "Autumn w2",
            "follower": "Pig",
        },
        "location": ["Everywhere"],
        "price": [2, 3, 4, 4, 6],
    },
    "Salmon": {
        "spawn": {"area": "River", "season": {"Summer", "Spring", "Autumn"}},
        "gatherable_type": "Fishing",
        "quality": {
            "tool": "Expert+",
            "time": "Evening",
            "season": "Spring",
            "trait": "Intelligence",
        },
        "location": ["Everywhere"],
        "price": [2, 3, 4, 4, 6],
    },
    "Silverscale": {
        "spawn": {"time": {"Morning", "Dawn", "Afternoon", "Evening", "Dusk"}},
        "gatherable_type": "Fishing",
        "quality": {
            "tool": "Adept+",
            "time": "Dusk",
            "time": "Freylsday (5)",
            "weather": "Hot",
        },
        "location": ["Everywhere"],
        "price": [1, 1, 2, 2, 3],
    },
    "Swamflatch": {
        "gatherable_type": "Fishing",
        "quality": {
            "follower": "Bumbabloopfnoop",
            "tool": "Artisan+",
            "trait": "Constitution",
            "weather": "Strange",
        },
        "location": ["Tir Na Nog"],
        "price": [5, 8, 10, 12, 15],
    },
    "WeedSkimmer": {
        "spawn": {"area": "River", "season": {"Summer", "Winter", "Autumn"}},
        "gatherable_type": "Fishing",
        "quality": {
            "season": {"Summer"},
            "tool": "Journeyman+",
            "trait": "Speed",
            "trait": "Constitution",
        },
        "location": ["Tir Na Nog"],
        "price": [5, 8, 10, 12, 15],
    },
    "TinOre": {
        "gatherable_type": "Mining",
        "quality": {
            "misc": {"Lantern Off", "Blacksmith lvl 1+"},
            "trait": "Scent",
            "tool": "Craftsman+",
        },
        "location": [
            "Crumblechalk Mine",
            "Burial Grounds",
            "Festival Green",
            "North Gate",
            "Deep Mine",
        ],
        "price": [1, 1, 2, 2, 3],
    },
    "CopperOre": {
        "gatherable_type": "Mining",
        "quality": {
            "misc": {"Lantern Off", "Blacksmith lvl 2+"},
            "trait": "Constitution",
            "tool": "Craftsman+",
        },
        "location": ["Poppyhill", "Homesteads", "Deep Mine"],
        "price": [3, 5, 7, 8, 10],
    },
    "ZincOre": {
        "gatherable_type": "Mining",
        "quality": {
            ### Not sure about Lantern
            "misc": {"Lantern Off", "Blacksmith lvl 3+"},
            "trait": "Stench",
            "tool": "Craftsman+",
        },
        "location": ["Mellowbrook", "Mellowmine", "Deep Mine"],
        "price": [4, 7, 9, 10, 13],
    },
    "IronOre": {
        "gatherable_type": "Mining",
        "quality": {
            "misc": {"Blacksmith lvl 6+"},
            "follower": "Any Animal",
            "trait": "Negativity",
            "tool": "Artisan+",
        },
        "location": ["Poppyhill", "Homesteads", "Deep Mine"],
        "price": [1, 2, 3, 3, 4],
    },
    "LuminiumOre": {
        "gatherable_type": "Mining",
        "quality": {
            "misc": {"Blacksmith lvl 8+"},
            "time": "Afternoon",
            "trait": "Bravery",
            "tool": "Legendary+",
        },
        "location": ["Tir Na Nog"],
        "price": [4, 7, 9, 10, 13],
    },
    "ShadderwrythOre": {
        "gatherable_type": "Mining",
        "quality": {
            "misc": {"Blacksmith lvl 7+"},
            "time": "Night",
            "trait": "Blessed",
            "tool": "Master+",
        },
        "location": ["Tir Na Nog"],
        "price": [3, 5, 7, 8, 10],
    },
    "Apple": {
        "gatherable_type": "Shooting",
        "quality": {
            "time": {"Afternoon", "Solsday (7)"},
            "ride": "Pig",
            "tool": "Craftsman+",
        },
        "location": ["Vale"],
        "price": [1, 1, 1, 1, 1],
    },
    "BlueBerry": {
        "gatherable_type": "Shooting",
        "quality": {
            "time": {"Dawn", "Woesday (3)"},
            "follower": "Dog",
            "tool": "Adept+",
        },
        "location": ["Vale"],
        "price": [1, 1, 2, 2, 3],
    },
    "BogeymanFungus": {
        "gatherable_type": "Gathering",
        "quality": {
            "follower": "Fillifryth",
            "season": "Summer w1",
            "tool": "Master+",
            "misc": "All Explorer skills",
        },
        "location": ["Ferrous Footway", "Deep Mine"],
        "price": [15, 24, 30, 36, 45],
    },
    "DuskCherry": {
        "gatherable_type": "Shooting",
        "quality": {
            "weather": "Under Moonbeams",
            "follower": "Bumbabloopfnoop",
            "tool": "Legendary+",
            "time": "Truthsday (2)",
        },
        "location": ["E'ergreen"],
        "price": [3, 5, 7, 8, 10],
    },
    "Eldersberry": {
        "gatherable_type": "Shooting",
        "quality": {
            "follower": "Bumbabloopfnoop",
            "tool": "Expert+",
            "time": {"Night", "Midnight"},
        },
        "location": ["E'ergreen"],
        "price": [3, 4, 6, 7, 9],
    },
    "Gooseberry": {
        "gatherable_type": "Shooting",
        "quality": {
            "follower": "Pig",
            "tool": "Adept+",
            "time": {"Dawn"},
            "weather": "Rain",
        },
        "location": ["Poppyhill"],
        "price": [3, 4, 6, 7, 9],
    },
    "Grapes": {
        "gatherable_type": "Shooting",
        "quality": {
            "tool": "Craftsman+",
            "time": {"Dawn", "Satyrsday (6)"},
            "weather": "Hot",
        },
        "location": ["Cunning Plots", "Outlane"],
        "price": [1, 2, 3, 3, 4],
    },
    "GummyMushroom": {
        "gatherable_type": "Gathering",
        "quality": {
            "tool": "Adept+",
            "time": {"Solsday (7)"},
            "weather": "Foggy",
            "trait": "Clumsy",
        },
        "location": ["Tir Na Nog", "The Tawnging Gardens"],
        "price": [1, 4, 5, 6, 7],
    },
    "Moxy": {
        "gatherable_type": "Gathering",
        "quality": {
            "tool": "Legendary+",
            "season": "Winter w2",
            "weather": "Foggy",
            "trait": "Healing",
        },
        "location": ["Dreadwaters"],
        "price": [7, 12, 15, 18, 22],
    },
    "Mushroom": {
        "gatherable_type": "Gathering",
        "quality": {
            "ride": "Pig",
            "season": "Autumn w2",
            "weather": "Rain",
            "tool": "Adept+",
        },
        "location": ["Mellowmine", "Crumblechalk Mine", "Burial Grounds"],
        "price": [1, 1, 2, 2, 3],
    },
    "Nightberry": {
        "gatherable_type": "Shooting",
        "quality": {
            "season": "Autumn",
            "time": {"Midnight", "Moonsday (1)"},
            "tool": "Master+",
        },
        "location": ["North gate", "The Twanging Gardens", "Loverwood", "Candlewych Cottage/West"],
        "price": [2, 3, 4, 4, 6],
    },
    "RainbowMushroom": {
        "gatherable_type": "Gathering",
        "quality": {
            "season": "Autumn w1",
            "follower": "Pig",
            "weather": "Sunny",
            "tool": "Expert+",
        },
        "location": ["Cuckoo Wood", "Burial Grounds", "Mosswhisper Ruin", "North Gate", "Drownhill", "Mellowbrook", "Cunning Plots"],
        "price": [2, 4, 5, 6, 7],
    },
    "SugarPlums": {
        "gatherable_type": "Shooting",
        "quality": {
            "has": "Lover",
            "tool": "Expert+",
            "weather": "Foggy",
            "trait": "Cursed",
        },
        "location": ["Tir Na Nog"],
        "price": [2, 4, 5, 6, 7],
    },
    "SilverNox": {
        "gatherable_type": "Shooting",
        "quality": {
        },
        "location": ["The Twanging Gardens"],
        "price": [50, 80, 100, 120, 150],
    },
    "AloeVera": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": "Dusk",
            "season": "Spring w1",
            "weather": "Windy",
            "follower": "Pig",
        },
        "location": ["Poppyhill"],
        "price": [1, 1, 2, 2, 3],
    },
    "Basil": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Dawn", "Even days"},
            "season": "Autumn w1",
            "weather": "Rain",
        },
        "location": ["Mellowfields"],
        "price": [1, 1, 2, 2, 3],
    },
    "BlindMary": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Evening", "Woesday (3)"},
            "season": "Winter",
            "misc": "Lantern Off",
        },
        "location": ["Wisptrail", "Greymarket"],
        "price": [1, 1, 2, 2, 3],
    },
    "Bogbean": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Night", "Moonsday (1)"},
            "season": "Autumn",
            "weather": "Rain",
        },
        "location": ["Woemarsh"],
        "price": [6, 9, 12, 14, 18],
    },
    "Caorthann": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Afternoon"},
            "season": "Spring",
            "follower": {"Bumbabloopfnoop", "Fillifryth"},
        },
        "location": ["E'ergreen"],
        "price": [2, 4, 5, 6, 7],
    },
    "Catnip": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Afternoon"},
            "season": "Summer w2",
            "weather": "Overcast",
            "follower": {"Cat"},
        },
        "location": ["Cunning Plots", "Terrarium", "The Twanging Gardens"],
        "price": [1, 1, 2, 2, 3],
    },
    "Charmweed": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Afternoon",},
            "season": "Autumn",
            "weather": "Rain",
            "follower": "Spouse",
        },
        "location": ["Drownhill", "FestField", "Homesteads", "Loverwood", "Rivermoor", "Tir Na Nog"],
        "price": [3, 4, 6, 7, 9],
    },
    "Coriander": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Evening",},
            "season": "Spring w2",
            "weather": "Sunny",
            "follower": "Sheep",
        },
        "location": ["Candlewych Cottage"],
        "price": [1, 1, 2, 2, 3],
    },
    "CuckooDew": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Morning", "Woesday (3)"},
            "season": "Summer",
            "weather": "Rain",
        },
        "location": ["Candlewych Cottage", "Cuckoo Wood", "Burial Grounds", "Festival Green", "Outlane"],
        "price": [1, 1, 2, 2, 3],
    },
    "Dandelion": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Dawn",},
            "season": "Summer",
            "weather": "Mild",
        },
        "location": ["Everywhere"],
        "price": [1, 1, 0, 0, 0],
    },
    "DankMoss": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Evening",},
            "weather": "Foggy",
            "misc": "Lantern Off",
        },
        "location": ["Cuckoo Wood"],
        "price": [2, 4, 5, 6, 7],
    },
    "Garlic": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Dawn", "Solsday (7)",},
            "season": "Summer w1",
            "weather": "Hot",
        },
        "location": ["Cuckoo Wood"],
        "price": [1, 1, 2, 2, 3],
    },
    "Ginger": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Afternoon",},
            "season": "Summer w2",
            "weather": "Hot",
            "follower": "Dog",
        },
        "location": ["Cunning Plots, Mellowbrook", "Terrarium", "The Twanging Gardens"],
        "price": [1, 1, 2, 2, 3],
    },
    "LittleSap": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Evening",},
            "season": "Spring",
            "weather": "Foggy",
            "follower": "Any Animal",
        },
        "location": ["Homesteads", "Tir Na Nog", "Dreamer's Nook"],
        "price": [10, 16, 20, 24, 30],
    },
    "Luachra": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Morning", "Exact Hour"},
            "season": "Spring",
            "trait": "Illusion",
        },
        "location": ["E'ergreen", "The Twanging Gardens"],
        "price": [2, 4, 5, 6, 7],
    },
    "Mandrake": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Dusk"},
            "weather": "Overcast",
            "season": "Autumn",
            "trait": "Toughness",
        },
        "location": ["Frogmarsh", "Dreadwaters"],
        "price": [16, 26, 33, 39, 49],
    },
    "Marshmallow": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Dusk"},
            "weather": "Sunny",
            "season": "Winter w2",
            "follower": "Bumbabloopfnoop",
        },
        "location": ["Swamp Boutique", "Copperpot"],
        "price": [1, 1, 2, 2, 3],
    },
    "MilkMoss": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Morning", "Dawn"},
            "weather": "Spring",
            "follower": "Cat",
        },
        "location": ["Cuckoo Wood"],
        "price": [2, 4, 5, 6, 7],
    },
    "Mint": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Dawn"},
            "season": "Spring w1",
            "weather": "Blizzard",
            "trait": "Scent",
        },
        "location": ["Poppyhill", "Terrarium", "The Twanging Gardens"],
        "price": [1, 1, 2, 2, 3],
    },
    "Nettle": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Morning"},
            "season": "Autumn",
            "weather": "Foggy",
            "has": "Hater",
        },
        "location": ["Naida's Glory", "Outlanes"],
        "price": [1, 1, 2, 2, 3],
    },
    "Parsley": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Dawn"},
            "season": "Spring w1",
            "weather": "Rain",
            "trait": "Scent",
        },
        "location": ["Poppyhill", "Naida's Glory", "Outlanes"],
        "price": [1, 1, 2, 2, 3],
    },
    "SceachGheal": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Evening"},
            "season": "Spring",
            "weather": "Pollen",
            "trait": "Illusion",
        },
        "location": ["E'ergreen"],
        "price": [2, 4, 5, 6, 7],
    },
    "Spearwort": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Afternoon", "Satyrsday (6)"},
            "season": "Summer",
            "weather": "Storm",
        },
        "location": ["Wisptrail", "Copperpot", "Frogmarsh", "Greymarket"],
        "price": [1, 2, 3, 3, 4],
    },
    "SweetMoss": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Afternoon"},
            "season": "Winter",
            "weather": "Bubbles",
            "follower": "Bumbabloopfnoop",
        },
        "location": ["Cuckoo Wood"],
        "price": [2, 4, 5, 6, 7],
    },
    "Thyme": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Dawn", "Exact Hour"},
            "season": "Summer w1",
            "ride": "Pig",
        },
        "location": ["Candlewych Cottage/Village", "Mellowbrook", "Willowdown Farm"],
        "price": [1, 1, 2, 2, 3],
    },
    "Ullisis": {
        "gatherable_type": "Gathering",
        "quality": {
            "time": {"Night", "Midnight"},
            "weather": "Pollen",
        },
        "location": ["E'ergreen", "The Twanging Gardens"],
        "price": [4, 6, 8, 9, 12],
    },
    "Whistleroot": {
        "gatherable_type": "Gathering",
        "quality": {
            "season": "Spring w2",
            "tool": "Master+",
            "weather": "Windy",
            "misc": "Lantern Off",
        },
        "location": ["Dreamer's Nook", "Tir Na Nog", "Willowdown Farm"],
        "price": [6, 9, 12, 14, 18],
    },
}
